NETWORK_NAME="dev-tools-net"

MYSQL_IMAGE="mysql:latest"
MYSQL_CONTAINER_NAME="mysql-db"
MYSQL_ROOT_PASSWORD="my-secret-pw"
MYSQL_DATABASE="our-app-db"
MYSQL_PORT="3306"
MYSQL_HOST_PORT="3306"

JOOMLA_IMAGE="joomla:latest"
JOOMLA_CONTAINER_NAME="joomla-app"
JOOMLA_USER="root"
JOOMLA_PORT="8080"
JOOMLA_HOST_PORT="80"
JOOMLA_SITE_NAME="Dev Tools Final Project"
JOOMLA_ADMIN_USERNAME="demoadmin"
JOOMLA_ADMIN_PASSWORD="secretpassword"
JOOMLA_ADMIN_EMAIL="admin@joomla.com"
JOOMLA_ADMIN_FULL_NAME="Admin Admin"

echo "Creating docker network"
docker network create "$NETWORK_NAME"

docker pull "$MYSQL_IMAGE"
docker pull "$JOOMLA_IMAGE"

docker run -d \
  --name "$MYSQL_CONTAINER_NAME" \
  --network "$NETWORK_NAME" \
  -e MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD" \
  -e MYSQL_DATABASE="$MYSQL_DATABASE" \
  -p "$MYSQL_PORT:$MYSQL_HOST_PORT" \
  "$MYSQL_IMAGE"

docker run -d \
  --name "$JOOMLA_CONTAINER_NAME" \
  --network "$NETWORK_NAME" \
  -e JOOMLA_DB_HOST="$MYSQL_CONTAINER_NAME" \
  -e JOOMLA_DB_USER="$JOOMLA_USER" \
  -e JOOMLA_DB_PASSWORD="$MYSQL_ROOT_PASSWORD" \
  -e JOOMLA_DB_NAME="$MYSQL_DATABASE" \
  -e JOOMLA_SITE_NAME="$JOOMLA_SITE_NAME" \
  -e JOOMLA_ADMIN_USER="$JOOMLA_ADMIN_FULL_NAME" \
  -e JOOMLA_ADMIN_USERNAME="$JOOMLA_ADMIN_USERNAME" \
  -e JOOMLA_ADMIN_PASSWORD="$JOOMLA_ADMIN_PASSWORD" \
  -e JOOMLA_ADMIN_EMAIL="$JOOMLA_ADMIN_EMAIL" \
  -p "$JOOMLA_PORT:$JOOMLA_HOST_PORT" \
  "$JOOMLA_IMAGE"